### PR TITLE
Use --dev flag

### PR DESCRIPTION
**Pull request by barryvdh**
Installs Deployer only for development by default.

### CODE REVIEW

**Comment by antonmedv** [comment]
Thanks. But I'm now satisfied with this repo at all. I'm going to deprecate it in Deployer v7 and figure out something better.

**Comment by barryvdh** [comment]
What don't you like? I like the idea of having deployer fixed with the source code, in case of breaking changes to the deploy.php file. So before I was just downloading the phar to bin/deployer and add it to git, but this seems cleaner.

**Comment by kszymukowicz** [comment]
Yes. I also like deployphp/distribution 👍

**Comment by antonmedv** [comment]
> So before I was just downloading the phar to bin/deployer and add it to git, but this seems cleaner.

I think this more straight solution? Isn't it?

**Comment by barryvdh** [comment]
Except that it doesn't get updated, while setting it to `^6` in the require-dev section, does provide bugfixes/improvements while remaining compatible.

**Comment by antonmedv** [comment]
But self-update functionality? Maybe include self updating check?

**Comment by barryvdh** [comment]
Wouldn't make it much easier than it is now. What is the problem with the current solution?

**Comment by antonmedv** [comment]
What I need to manually create a release with tag.

**Pull request merged**
